# Generated by Django 2.1 on 2020-01-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SplashPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SplashPageName', models.CharField(max_length=20)),
                ('SVGField', models.TextField()),
                ('UseAnimation', models.BooleanField()),
                ('BackgroundColorString', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Splash Page',
                'verbose_name_plural': 'Splash Page',
            },
        ),
    ]
