version: '3'

services :
  database:
    image: database
    ports:
      - "3306:3306"
    volumes:
      - data-volume:/var/lib/mysql
    env_file:
      - databasesecrets.env
  magic_mirror:
    image: magicmirror:latest
    command: python3 manage.py runserver
    ports:
      - "80:8000"
    depends_on:
      - database
    env_file:
      - mirrorsecrets.env


volumes:
  data-volume: