version: '3'

services :
  database:
    image: hypriot/rpi-mysql
    volumes:
      - data-volume:/var/lib/db
  magic_mirror:
    image: magicmirror:latest
    command: python3 manage.py runserver
    ports:
      - "80:8000"
    depends_on:
      - database

volumes:
  data-volume