version: '3'

services :
  database:
    image: hypriot/rpi-mysql
    volumes:
      - C:\Users\Daniel\Git\MagicMirror\Data
  magic_mirror:
    image: magicmirror:latest
    command: python3 manage.py runserver
    ports:
      - "80:8000"
    depends_on:
      - database
    env_file:
      - secrets.env


volumes:
  data-volume: