# Generated by Django 2.1 on 2020-01-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextSatementSourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=500)),
                ('source_site', models.CharField(choices=[('RE', 'Reddit'), ('TWI', 'Twitter')], default='RE', max_length=10)),
                ('last_update_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TextStatementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_text', models.CharField(max_length=500)),
                ('statement_author', models.CharField(max_length=500, null=True)),
                ('statement_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statements.TextSatementSourceModel')),
            ],
        ),
    ]
