# Generated by Django 2.1 on 2018-08-23 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCSSFileBridgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'App / CSS Bridge',
                'verbose_name_plural': 'App / CSS Bridges',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDefinitionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Application Name')),
                ('bundlePath', models.CharField(max_length=100, verbose_name='Javascript Bundle Name')),
                ('hasCSS', models.BooleanField()),
                ('width_value', models.IntegerField(verbose_name='Width')),
                ('width_unit', models.CharField(max_length=10, verbose_name='Width Units')),
                ('height_value', models.IntegerField(verbose_name='Height')),
                ('height_unit', models.CharField(max_length=10, verbose_name='Height Units')),
            ],
            options={
                'verbose_name': 'Application Definition',
                'verbose_name_plural': 'Application Definitions',
            },
        ),
        migrations.CreateModel(
            name='ApplicationUIBridgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'App UI Bridge',
                'verbose_name_plural': 'App UI Bridges',
            },
        ),
        migrations.CreateModel(
            name='ApplicationUIConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startRow', models.IntegerField(verbose_name='Start Row')),
                ('endRow', models.IntegerField(verbose_name='End Row')),
                ('startColumn', models.IntegerField(verbose_name='Start Column')),
                ('endColumn', models.IntegerField(verbose_name='End Column')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('startOnStartup', models.BooleanField(verbose_name='Should Load On Start')),
            ],
            options={
                'verbose_name': 'App UI Configuration',
                'verbose_name_plural': 'App UI Configurations',
            },
        ),
        migrations.CreateModel(
            name='CSSResourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcePath', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CSS File',
                'verbose_name_plural': 'CSS Files',
            },
        ),
        migrations.CreateModel(
            name='FontModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Font Name')),
                ('url', models.CharField(max_length=1000, verbose_name='Font URL')),
            ],
            options={
                'verbose_name': 'Font',
                'verbose_name_plural': 'Fonts',
            },
        ),
        migrations.CreateModel(
            name='MagicMirrorConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField(verbose_name='Rows')),
                ('columns', models.IntegerField(verbose_name='Columns')),
                ('width_value', models.IntegerField(verbose_name='Width')),
                ('width_unit', models.CharField(max_length=10)),
                ('height_value', models.IntegerField(verbose_name='Height')),
                ('height_unit', models.CharField(max_length=10)),
                ('startUpApp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ApplicationDefinitionModel')),
            ],
            options={
                'verbose_name': 'Magic Mirror Configuration',
                'verbose_name_plural': 'Magic Mirror Configurations',
            },
        ),
        migrations.CreateModel(
            name='UserAppListBridgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ApplicationDefinitionModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User App List',
                'verbose_name_plural': 'User App Lists',
            },
        ),
        migrations.AddField(
            model_name='applicationuibridgemodel',
            name='UI_Config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ApplicationUIConfigModel', verbose_name='Configuration'),
        ),
        migrations.AddField(
            model_name='applicationuibridgemodel',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ApplicationDefinitionModel', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='applicationcssfilebridgemodel',
            name='actualApp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ApplicationDefinitionModel', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='applicationcssfilebridgemodel',
            name='css_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CSSResourceModel', verbose_name='CSS File'),
        ),
    ]
