# Generated by Django 2.1 on 2019-04-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_squashed_0013_delete_magicmirroruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicMirrorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
            ],
        ),
    ]
