# Generated by Django 2.1 on 2018-08-23 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcssfilebridgemodel',
            name='actualApp',
            field=models.ForeignKey(help_text='ASDF', on_delete=django.db.models.deletion.CASCADE, to='home.ApplicationDefinitionModel', verbose_name='Application'),
        ),
    ]
