# Generated by Django 2.1 on 2019-04-14 05:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_magicmirroruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('width_value', models.IntegerField()),
                ('width_unit', models.CharField(choices=[('cm', 'Centimeters'), ('mm', 'Millimeters'), ('in', 'Inches'), ('px', 'Pixels'), ('pt', 'Points'), ('pc', 'Picas'), ('em', 'Relative to font-size'), ('ex', 'Relative to x-height'), ('ch', 'Relative to the "0" character'), ('rem', 'Relative to font size of root element'), ('vm', 'Relative to width of viewport'), ('vh', 'Relative to height of viewport'), ('vmin', 'Min of vm and vh'), ('vmax', 'Max of vm and vh'), ('%', 'Percent')], max_length=20)),
                ('height_value', models.IntegerField(verbose_name='Height')),
                ('height_unit', models.CharField(choices=[('cm', 'Centimeters'), ('mm', 'Millimeters'), ('in', 'Inches'), ('px', 'Pixels'), ('pt', 'Points'), ('pc', 'Picas'), ('em', 'Relative to font-size'), ('ex', 'Relative to x-height'), ('ch', 'Relative to the "0" character'), ('rem', 'Relative to font size of root element'), ('vm', 'Relative to width of viewport'), ('vh', 'Relative to height of viewport'), ('vmin', 'Min of vm and vh'), ('vmax', 'Max of vm and vh'), ('%', 'Percent')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeviceBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DeviceModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MagicMirrorUser')),
            ],
        ),
    ]
