# Generated by Django 2.1 on 2018-08-23 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180822_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcssfilebridgemodel',
            name='actualApp',
            field=models.ForeignKey(help_text='Application you want to associate a CSS File with', on_delete=django.db.models.deletion.CASCADE, to='home.ApplicationDefinitionModel', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='applicationcssfilebridgemodel',
            name='css_resource',
            field=models.ForeignKey(help_text='CSS file to be loaded when the application is loaded', on_delete=django.db.models.deletion.CASCADE, to='home.CSSResourceModel', verbose_name='CSS File'),
        ),
    ]
