# Generated by Django 2.1 on 2019-04-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_devicemodel_userdevicebridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='name',
            field=models.CharField(default='DevBox', max_length=200),
            preserve_default=False,
        ),
    ]
