# Generated by Django 2.1 on 2018-08-23 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180822_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdefinitionmodel',
            name='bundlePath',
            field=models.CharField(help_text='Location of the Javascript bundle that defines the app. Relative to the the /static/ endpoint', max_length=100, verbose_name='Javascript Bundle Name'),
        ),
        migrations.AlterField(
            model_name='applicationdefinitionmodel',
            name='name',
            field=models.CharField(help_text='Friendly name to use to refer to this application.', max_length=50, verbose_name='Application Name'),
        ),
        migrations.AlterField(
            model_name='applicationuibridgemodel',
            name='UI_Config',
            field=models.ForeignKey(help_text='UI configuration that defines how the app should appear', on_delete=django.db.models.deletion.CASCADE, to='home.ApplicationUIConfigModel', verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='applicationuibridgemodel',
            name='app',
            field=models.ForeignKey(help_text='Application to use with a particular UI configuration', on_delete=django.db.models.deletion.CASCADE, to='home.ApplicationDefinitionModel', verbose_name='Application'),
        ),
    ]
