# Generated by Django 2.1 on 2019-04-14 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_devicemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevicebridge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
