# Generated by Django 2.1 on 2018-08-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180822_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuiconfigmodel',
            name='endColumn',
            field=models.IntegerField(help_text='The last column that this app should take up in the CSS Grid. Exclusive', verbose_name='End Column'),
        ),
        migrations.AlterField(
            model_name='applicationuiconfigmodel',
            name='endRow',
            field=models.IntegerField(help_text='The last row that this app should take up in the CSS Grid. Exclusive', verbose_name='End Row'),
        ),
        migrations.AlterField(
            model_name='applicationuiconfigmodel',
            name='name',
            field=models.CharField(help_text='Friendly name to refer to this UI configuration.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='applicationuiconfigmodel',
            name='startColumn',
            field=models.IntegerField(help_text='The first column that this app should take up in the CSS Grid. Starts at 1', verbose_name='Start Column'),
        ),
        migrations.AlterField(
            model_name='applicationuiconfigmodel',
            name='startRow',
            field=models.IntegerField(help_text='The first row that this app should take up in the CSS Grid. Starts at 1', verbose_name='Start Row'),
        ),
    ]
