# Generated by Django 2.1 on 2018-08-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180822_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicmirrorconfigmodel',
            name='configurationName',
            field=models.CharField(default='MainConfig', help_text='Friendly name to use to refer to this configuration', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cssresourcemodel',
            name='sourcePath',
            field=models.CharField(help_text='Location of the CSS file relative to the /static/ endpoint', max_length=255),
        ),
        migrations.AlterField(
            model_name='fontmodel',
            name='name',
            field=models.CharField(help_text='Friendly name to use to refer to this font', max_length=100, verbose_name='Font Name'),
        ),
        migrations.AlterField(
            model_name='fontmodel',
            name='url',
            field=models.CharField(help_text='URL to use to load the font', max_length=1000, verbose_name='Font URL'),
        ),
        migrations.AlterField(
            model_name='magicmirrorconfigmodel',
            name='columns',
            field=models.IntegerField(help_text='Number of columns to use in the main MagicMirror grid', verbose_name='Columns'),
        ),
        migrations.AlterField(
            model_name='magicmirrorconfigmodel',
            name='height_value',
            field=models.IntegerField(help_text='Number of whatever column unit desired', verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='magicmirrorconfigmodel',
            name='rows',
            field=models.IntegerField(help_text='Number of rows to use in the main MagicMirror grid', verbose_name='Rows'),
        ),
        migrations.AlterField(
            model_name='magicmirrorconfigmodel',
            name='width_value',
            field=models.IntegerField(help_text='Number of whatever width unit desired', verbose_name='Width'),
        ),
    ]
