# Generated by Django 2.1 on 2019-04-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    atomic=False

    dependencies = [
        ('home', '0005_auto_20190413_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemodel',
            old_name='id',
            new_name='deviceId',
        ),
    ]
