# Generated by Django 2.1 on 2019-04-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190414_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevicebridge',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DeviceModel'),
        ),
    ]
