# Generated by Django 2.1 on 2018-08-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180826_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdefinitionmodel',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('mm', 'Millimeters'), ('in', 'Inches'), ('px', 'Pixels'), ('pt', 'Points'), ('pc', 'Picas'), ('em', 'Relative to font-size'), ('ex', 'Relative to x-height'), ('ch', 'Relative to the "0" character'), ('rem', 'Relative to font size of root element'), ('vm', 'Relative to width of viewport'), ('vh', 'Relative to height of viewport'), ('vmin', 'Min of vm and vh'), ('vmax', 'Max of vm and vh'), ('%', 'Percent')], max_length=20, verbose_name='Height Units'),
        ),
        migrations.AlterField(
            model_name='applicationdefinitionmodel',
            name='name',
            field=models.CharField(help_text='Friendly name to use to refer to this application.', max_length=200, verbose_name='Application Name'),
        ),
        migrations.AlterField(
            model_name='applicationdefinitionmodel',
            name='width_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('mm', 'Millimeters'), ('in', 'Inches'), ('px', 'Pixels'), ('pt', 'Points'), ('pc', 'Picas'), ('em', 'Relative to font-size'), ('ex', 'Relative to x-height'), ('ch', 'Relative to the "0" character'), ('rem', 'Relative to font size of root element'), ('vm', 'Relative to width of viewport'), ('vh', 'Relative to height of viewport'), ('vmin', 'Min of vm and vh'), ('vmax', 'Max of vm and vh'), ('%', 'Percent')], max_length=20, verbose_name='Width Units'),
        ),
        migrations.AlterField(
            model_name='applicationuiconfigmodel',
            name='name',
            field=models.CharField(help_text='Friendly name to refer to this UI configuration.', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cssresourcemodel',
            name='sourcePath',
            field=models.CharField(help_text='Location of the CSS file relative to the /static/ endpoint', max_length=100),
        ),
        migrations.AlterField(
            model_name='fontmodel',
            name='name',
            field=models.CharField(help_text='Friendly name to use to refer to this font', max_length=200, verbose_name='Font Name'),
        ),
        migrations.AlterField(
            model_name='magicmirrorconfigmodel',
            name='configurationName',
            field=models.CharField(help_text='Friendly name to use to refer to this configuration', max_length=200),
        ),
        migrations.AlterField(
            model_name='magicmirrorconfigmodel',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('mm', 'Millimeters'), ('in', 'Inches'), ('px', 'Pixels'), ('pt', 'Points'), ('pc', 'Picas'), ('em', 'Relative to font-size'), ('ex', 'Relative to x-height'), ('ch', 'Relative to the "0" character'), ('rem', 'Relative to font size of root element'), ('vm', 'Relative to width of viewport'), ('vh', 'Relative to height of viewport'), ('vmin', 'Min of vm and vh'), ('vmax', 'Max of vm and vh'), ('%', 'Percent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='magicmirrorconfigmodel',
            name='width_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('mm', 'Millimeters'), ('in', 'Inches'), ('px', 'Pixels'), ('pt', 'Points'), ('pc', 'Picas'), ('em', 'Relative to font-size'), ('ex', 'Relative to x-height'), ('ch', 'Relative to the "0" character'), ('rem', 'Relative to font size of root element'), ('vm', 'Relative to width of viewport'), ('vh', 'Relative to height of viewport'), ('vmin', 'Min of vm and vh'), ('vmax', 'Max of vm and vh'), ('%', 'Percent')], max_length=20),
        ),
    ]
