# Generated by Django 2.1 on 2019-04-14 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190414_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='deviceId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
