# Generated by Django 2.1 on 2019-04-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190414_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='id',
            field=models.CharField(default='asdf', max_length=2),
            preserve_default=False,
        ),
    ]
