# Generated by Django 2.1 on 2019-04-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_devicemodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='id',
        ),
    ]
