# Generated by Django 2.1 on 2018-12-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_phonenumbermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumbermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='PhoneNumberModel',
        ),
    ]
