# Generated by Django 2.1 on 2019-04-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_devicemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='height_value',
            field=models.IntegerField(verbose_name='Heights'),
        ),
    ]
