# Generated by Django 2.1 on 2019-04-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190414_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='deviceId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
