# Generated by Django 2.1 on 2019-05-05 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190414_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagicMirrorUser',
        ),
        migrations.AlterField(
            model_name='applicationcssfilebridgemodel',
            name='css_resource',
            field=models.ForeignKey(help_text='CSS file to be loaded', on_delete=django.db.models.deletion.CASCADE, to='home.CSSResourceModel', verbose_name='CSS File'),
        ),
        migrations.AlterField(
            model_name='applicationdefinitionmodel',
            name='bundlePath',
            field=models.CharField(help_text='Javascript bundle file. Relative to /static/ endpoint', max_length=100, verbose_name='Javascript Bundle Name'),
        ),
        migrations.AlterField(
            model_name='applicationuibridgemodel',
            name='UI_Config',
            field=models.ForeignKey(help_text='UI configuration for the app', on_delete=django.db.models.deletion.CASCADE, to='home.ApplicationUIConfigModel', verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='applicationuiconfigmodel',
            name='endColumn',
            field=models.IntegerField(help_text='Exclusive', verbose_name='End Column'),
        ),
        migrations.AlterField(
            model_name='applicationuiconfigmodel',
            name='endRow',
            field=models.IntegerField(help_text='Exclusive', verbose_name='End Row'),
        ),
        migrations.AlterField(
            model_name='applicationuiconfigmodel',
            name='startColumn',
            field=models.IntegerField(help_text='Starts at 1', verbose_name='Start Column'),
        ),
        migrations.AlterField(
            model_name='applicationuiconfigmodel',
            name='startRow',
            field=models.IntegerField(help_text='Starts at 1', verbose_name='Start Row'),
        ),
        migrations.AlterField(
            model_name='cssresourcemodel',
            name='sourcePath',
            field=models.CharField(help_text='Relative to the /static/ endpoint', max_length=100),
        ),
    ]
