# Generated by Django 2.1 on 2020-01-01 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20190504_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicmirrorconfigmodel',
            name='default_user',
            field=models.ForeignKey(blank=True, help_text='User to default for this mirror configuration', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
