# Generated by Django 2.1 on 2020-01-26 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_name', models.CharField(max_length=200)),
                ('calendar_id', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('postalCode', models.CharField(max_length=200)),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique ID')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PathName', models.CharField(help_text='Friendly name to refer to this path.', max_length=200)),
                ('EndingLocation', models.ForeignKey(help_text='Ending position of the path', on_delete=django.db.models.deletion.CASCADE, related_name='ending_locations', to='traffic.LocationModel', verbose_name='End Location')),
                ('StartingLocation', models.ForeignKey(help_text='Starting position of the path', on_delete=django.db.models.deletion.CASCADE, related_name='starting_locations', to='traffic.LocationModel', verbose_name='Start Location')),
            ],
        ),
        migrations.CreateModel(
            name='PathEstimationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoCompute', models.BooleanField(verbose_name='Autocompute?')),
                ('expectedNumberSeconds', models.IntegerField(verbose_name='Best estimated guess for trip length')),
                ('pathInstance', models.ForeignKey(help_text='Relevant Path', on_delete=django.db.models.deletion.CASCADE, to='traffic.Path', verbose_name='Path Instance')),
            ],
        ),
        migrations.CreateModel(
            name='PathLengthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now=True)),
                ('record_time', models.TimeField(auto_now=True)),
                ('secondsPerTrip', models.IntegerField(verbose_name='Expected duration in seconds')),
                ('pathInstance', models.ForeignKey(help_text='Relevant Path', on_delete=django.db.models.deletion.CASCADE, to='traffic.Path', verbose_name='Path Instance')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.LocationModel'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
