# Generated by Django 2.1 on 2018-10-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='PathName',
            field=models.CharField(help_text='Friendly name to refer to this path.', max_length=200),
        ),
    ]
