# Generated by Django 2.1 on 2018-10-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20181015_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathEstimationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoCompute', models.BooleanField(verbose_name='Autocompute?')),
                ('expectedNumberSeconds', models.IntegerField(verbose_name='Best estimated guess for trip length')),
                ('pathInstance', models.ForeignKey(help_text='Relevant Path', on_delete=django.db.models.deletion.CASCADE, to='traffic.Path', verbose_name='Path Instance')),
            ],
        ),
    ]
