# Generated by Django 2.1 on 2018-10-16 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_pathestimationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathLengthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now=True)),
                ('record_time', models.TimeField(auto_now=True)),
                ('secondsPerTrip', models.IntegerField(verbose_name='Expected duration in seconds')),
                ('pathInstance', models.ForeignKey(help_text='Relevant Path', on_delete=django.db.models.deletion.CASCADE, to='traffic.Path', verbose_name='Path Instance')),
            ],
        ),
    ]
