# Generated by Django 2.1 on 2018-10-17 04:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_pathlengthmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='uniqueId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
