# Generated by Django 2.1 on 2018-08-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('high_temp', models.FloatField(blank=True, null=True)),
                ('main_temp', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('low_temp', models.FloatField(blank=True, null=True)),
                ('snow_amt', models.FloatField(blank=True, null=True)),
                ('rain_amt', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direct', models.IntegerField(blank=True, null=True)),
                ('icon_key', models.CharField(blank=True, max_length=500, null=True)),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherForcastModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('high_temp', models.FloatField(blank=True, null=True)),
                ('main_temp', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('low_temp', models.FloatField(blank=True, null=True)),
                ('snow_amt', models.FloatField(blank=True, null=True)),
                ('rain_amt', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
