# Generated by Django 2.1 on 2019-05-12 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_dailyweathermodel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherforcastmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weatherforcastmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weatherforcastmodel',
            name='humidity',
        ),
        migrations.AddField(
            model_name='weatherforcastmodel',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 0, 0), unique=True),
            preserve_default=False,
        ),
    ]
