# Generated by Django 2.1 on 2019-05-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20190512_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforcastmodel',
            name='locationName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
