# Generated by Django 2.1 on 2020-01-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20190519_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforcastmodel',
            name='icon_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
