# Generated by Django 2.1 on 2018-11-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiappmodel',
            name='othername',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
