# Generated by Django 2.1 on 2018-11-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiapp', '0002_multiappmodel_othername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiappmodel',
            name='othername',
        ),
    ]
